"""PHASE 4 -- is nest edge vorticity numerical contamination, or expected Davies shear?

The matched-domain investigation kept failing because the 22 m nest's boundary carried far more
vorticity than its interior.  Two hypotheses were live:

  (a) it is a BUG (boundary divergence from the projection / BC ordering), fixable;
  (b) it is INTRINSIC to Davies-zone nesting -- shear generated by nudging toward an interpolated
      parent field -- i.e. expected behaviour that a trusted-interior margin must exclude.

Evidence so far pointed at (b): the outer-face divergence does NOT track the edge vorticity
(direct-solver nest, face residual 1.28e-04, zeta edge/interior 323; lowmem 2.85e-01 -> 778 and
2.17e-01 -> 217 -- no monotone relationship).  But that was three points at one instant.  This
script builds the controlled matrix and, crucially, converts the answer into the number the
science actually needs: a TRUSTED-INTERIOR MARGIN IN METRES.

METRIC.  A nest is finer than its parent, so it legitimately resolves more -- a raw nest-vs-parent
difference is not contamination.  We therefore block-average the nest field back onto its parent
cells (the scales the parent can represent) and compare there:

    mismatch(d) = < | zeta_nest_restricted - zeta_parent | >   over cells at distance d from the
                  nest boundary, normalised by the interior plateau value

Contamination penetration = the distance at which mismatch(d) falls to within `PLATEAU_TOL` of
its interior plateau.  That is a physical LENGTH, reported in metres, and it is what the trusted
margin must exceed.

VARIED:  sponge physical width, sponge rate, relax-before/after-projection ordering,
parent/nest refinement ratio, projection path (direct vs low-memory, via nest size).
MEASURED: zeta mismatch, divergence, and the penetration depth, each vs distance in METRES.

Run:  python scratchpad/edge_vorticity_matrix.py            (CPU, ~minutes)
Env:  DEV=gpu to use the GPU; STEPS=n to change the evolution window.
"""
import os, sys, json, time
REPO = r"c:/Users/ileao/OneDrive/Documentos/met_h2o_nucleation_cfd_tornado"
sys.path.insert(0, os.path.join(REPO, "src"))
os.chdir(REPO)
import numpy as np, warnings; warnings.filterwarnings("ignore")

from storm_dynamics.config import build_storm_config
from storm_dynamics.core import StormSimulation
from storm_dynamics import nesting as nst, rotation as rot
from storm_dynamics.pressure_fft import anelastic_divergence

DEV = os.environ.get("DEV", "cpu")
STEPS = int(os.environ.get("STEPS", 8))
PLATEAU_TOL = float(os.environ.get("PLATEAU_TOL", 1.5))   # within 1.5x of the interior plateau
OUT = os.path.join(REPO, "outputs", "edge_vorticity"); os.makedirs(OUT, exist_ok=True)
LOG = os.path.join(OUT, "matrix.log"); open(LOG, "w").close()
_t0 = time.time()


def log(m):
    open(LOG, "a", encoding="utf-8").write("[%6.1fs] %s\n" % (time.time() - _t0, m))
    print(m, flush=True)


def matured_parent(nx=60, nz=40):
    sc = build_storm_config(preset="storm", nx=nx, ny=nx, nz=nz, Lx=nx * 600.0, Ly=nx * 600.0,
                            Lz=15000.0, duration=1.0, dt_max=3.0, drag=True, z_stretch=1.05,
                            C_s=0.20, device=DEV, periodic=True)
    sc.sim.physics.bubble_dtheta = 5.0
    p = StormSimulation(sc)
    for _ in range(20):
        p._step(p._dt())
    return p


def _zeta2d(sim, z_m=100.0):
    g = sim.grid; to = g.backend.to_cpu
    z = np.asarray(to(rot.vertical_vorticity(sim.state, g)))
    zc = np.asarray(to(g.zc))
    return z[:, :, int(np.argmin(np.abs(zc - z_m)))]


def _restrict(a, r):
    """Block-average a nest field onto its parent cells (refinement ratio r)."""
    n0, n1 = a.shape
    m0, m1 = n0 // r, n1 // r
    return a[:m0 * r, :m1 * r].reshape(m0, r, m1, r).mean(axis=(1, 3))


def measure(parent, nest, spec, refine):
    """Mismatch and divergence as a function of distance from the nest boundary, in METRES."""
    g = nest.grid
    zn = _restrict(np.abs(_zeta2d(nest)), refine)              # on parent-representable scales
    # the parent cells the nest covers
    i0 = int(round(spec.x0 / parent.grid.dx)); j0 = int(round(spec.y0 / parent.grid.dy))
    zp = np.abs(_zeta2d(parent))[i0:i0 + zn.shape[0], j0:j0 + zn.shape[1]]
    m = np.abs(zn - zp)                                        # mismatch on parent scales
    n = m.shape[0]
    idx = np.arange(n)
    db = np.minimum(np.minimum(idx[:, None], n - 1 - idx[:, None]),
                    np.minimum(idx[None, :], n - 1 - idx[None, :]))
    dx_p = float(parent.grid.dx)
    prof = []
    for d in range(0, n // 2):
        sel = db == d
        if sel.any():
            prof.append((d * dx_p, float(m[sel].mean())))
    # interior plateau = mean over the inner half of the profile
    tail = [v for _, v in prof[len(prof) // 2:]]
    plateau = float(np.mean(tail)) if tail else float("nan")
    # penetration: first distance at which the mismatch drops to within tol of the plateau
    pen = float("nan")
    for dm, v in prof:
        if plateau > 0 and v <= PLATEAU_TOL * plateau:
            pen = dm
            break
    # divergence, on the nest's own mesh
    to = g.backend.to_cpu
    zf = np.asarray(to(g.zf)); dzc = g.xp.asarray(zf[1:] - zf[:-1])
    dv = np.abs(np.asarray(to(anelastic_divergence(nest.state.u, nest.state.v, nest.state.w,
                                                   nest.rho0_c, nest.rho0_wface,
                                                   g.dx, g.dy, dzc))))
    u = np.asarray(to(nest.state.u)); rc = np.asarray(to(nest.rho0_c))
    dv = dv / float(rc.max() * max(np.abs(u).max(), 1e-9) / g.dx)
    nn = dv.shape[0]; ii = np.arange(nn)
    dbn = np.minimum(np.minimum(ii[:, None], nn - 1 - ii[:, None]),
                     np.minimum(ii[None, :], nn - 1 - ii[None, :]))
    return {"profile_m": prof, "plateau": plateau, "penetration_m": pen,
            "edge_mismatch": prof[0][1] if prof else float("nan"),
            "edge_over_plateau": (prof[0][1] / plateau) if (prof and plateau > 0) else float("nan"),
            "div_face0": float(dv[dbn == 0].max()), "div_interior": float(dv[dbn >= 12].max())}


def run_case(parent, sponge_m, rate, before, refine, ncx, nz):
    def spec_fn(g):
        return nst.NestSpec.aligned(g, i0=10, j0=10, ncx=ncx, ncy=ncx, refine=refine, nz=nz,
                                    z_stretch=1.077, relax_width_m=sponge_m, relax_rate=rate,
                                    relax_before_project=before)
    sims, _ = nst.run_multilevel_nest(parent, [spec_fn], window=STEPS * float(parent._dt()))
    nest = sims[-1]
    return measure(parent, nest, nest.spec, refine), nest


if __name__ == "__main__":
    log("PHASE 4: is nest edge vorticity a bug or intrinsic Davies shear?")
    p = matured_parent()
    log("parent %dx%dx%d dx=%.0f m, %d steps of spin-up"
        % (p.grid.nx, p.grid.ny, p.grid.nz, p.grid.dx, 20))
    results = []
    # (label, sponge_m, rate, relax_before_project, refine, ncx, nz)
    cases = [
        ("baseline  sponge=267 rate=.02 after ", 267.0, 0.02, False, 3, 20, 40),
        ("relax BEFORE projection            ", 267.0, 0.02, True,  3, 20, 40),
        ("sponge  89 m                       ",  89.0, 0.02, False, 3, 20, 40),
        ("sponge 800 m                       ", 800.0, 0.02, False, 3, 20, 40),
        ("rate 0.005 (4x gentler)            ", 267.0, 0.005, False, 3, 20, 40),
        ("rate 0.08  (4x stiffer)            ", 267.0, 0.08, False, 3, 20, 40),
        ("refine 2 (smaller jump)            ", 267.0, 0.02, False, 2, 20, 40),
        ("bigger nest (lowmem path)          ", 267.0, 0.02, False, 3, 30, 64),
    ]
    log("")
    log("%-36s %10s %11s %10s %11s %11s" %
        ("case", "penetr[m]", "edge/plateau", "plateau", "div face0", "div interior"))
    for label, sm, rt, bf, rf, ncx, nz in cases:
        try:
            r, _ = run_case(p, sm, rt, bf, rf, ncx, nz)
            results.append({"case": label.strip(), "sponge_m": sm, "rate": rt,
                            "relax_before_project": bf, "refine": rf, "ncx": ncx, "nz": nz, **r})
            log("%-36s %10.0f %11.2f %10.2e %11.2e %11.2e"
                % (label, r["penetration_m"], r["edge_over_plateau"], r["plateau"],
                   r["div_face0"], r["div_interior"]))
        except Exception as e:
            log("%-36s FAILED %r" % (label, e))
    json.dump(results, open(os.path.join(OUT, "matrix.json"), "w"), indent=1)

    ok = [r for r in results if r["penetration_m"] == r["penetration_m"]]
    if ok:
        pens = [r["penetration_m"] for r in ok]
        log("")
        log("PENETRATION DEPTH across the matrix: min %.0f m | median %.0f m | MAX %.0f m"
            % (min(pens), float(np.median(pens)), max(pens)))
        log("=> a trusted-interior margin must EXCEED the max, and must be expressed in METRES.")
        # does it scale with the sponge width?  (the (b) hypothesis)
        by_sponge = {r["sponge_m"]: r["penetration_m"] for r in ok
                     if r["rate"] == 0.02 and not r["relax_before_project"] and r["refine"] == 3
                     and r["ncx"] == 20}
        log("penetration vs SPONGE WIDTH (m): %s" % {k: round(v) for k, v in sorted(by_sponge.items())})
        by_rate = {r["rate"]: r["penetration_m"] for r in ok
                   if r["sponge_m"] == 267.0 and not r["relax_before_project"] and r["refine"] == 3
                   and r["ncx"] == 20}
        log("penetration vs SPONGE RATE  (1/s): %s" % {k: round(v) for k, v in sorted(by_rate.items())})
    log("wrote %s" % os.path.join(OUT, "matrix.json"))
